apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
  namespace: mytest
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
  selector:
    app: spring-boot